# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      TZ: Asia/Taipei
      MONGO_INITDB_DATABASE: file-management
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./mongodb/init.d:/docker-entrypoint-initdb.d
    ports:
      - 27016:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017?authSource=admin

  # nginx:
  #   image: nginx
  #   restart: always
  #   ports:
  #     - 80:80

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - 3000:3000
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80

volumes:
  mongo-data:
    driver: local
